devices:
  bf0987654321fedcba:
    entities:
    - dps:
        switch: 1
      friendly_name: Smart Plug Power
      icon: mdi:power-socket
      name: Power
      platform: switch
    - device_class: current
      dps:
        value: 4
      friendly_name: Current Consumption
      icon: mdi:current-ac
      name: Current
      platform: sensor
      unit_of_measurement: mA
    - device_class: power
      dps:
        value: 5
      friendly_name: Power Consumption
      icon: mdi:flash
      name: Power
      platform: sensor
      scale: 0.1
      unit_of_measurement: W
    - device_class: voltage
      dps:
        value: 6
      friendly_name: Voltage
      icon: mdi:sine-wave
      name: Voltage
      platform: sensor
      scale: 0.1
      unit_of_measurement: V
    ip: 192.168.1.101
    local_key: another_local_key
    name: Smart Plug
    version: '3.3'
  bf1122334455667788:
    entities:
    - dps:
        oscillate: 3
        speed: 2
        switch: 1
      friendly_name: Ceiling Fan
      icon: mdi:fan
      name: Fan
      platform: fan
      speed_range:
      - 1
      - 3
    - brightness_range:
      - 10
      - 1000
      dps:
        brightness: 10
        switch: 9
      friendly_name: Fan Light
      icon: mdi:lightbulb
      name: Fan Light
      platform: light
    ip: 192.168.1.102
    local_key: fan_local_key
    name: Ceiling Fan
    version: '3.3'
  bf1234567890abcdef:
    entities:
    - brightness_range:
      - 10
      - 1000
      color_temp_range:
      - 0
      - 1000
      dps:
        brightness: 2
        color: 5
        color_mode: 4
        color_temp: 3
        switch: 1
      friendly_name: Living Room Main Light
      icon: mdi:lightbulb
      name: Main Light
      platform: light
    ip: 192.168.1.100
    local_key: your_local_key_here
    name: Living Room Light
    version: '3.3'
homeassistant:
  enabled: true
mqtt:
  base_topic: tuya2mqtt
  discovery_prefix: homeassistant
  host: localhost
  password: null
  port: 1883
  username: null
poll_interval: 30
web:
  enabled: true
  port: 8099
